# Generated by Django 2.1.5 on 2021-08-04 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20210803_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likedCategories',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rango.Category'),
            preserve_default=False,
        ),
    ]
