# Generated by Django 2.1.5 on 2021-08-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_userprofile_likedcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='likedCategories',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likedCategories',
            field=models.ManyToManyField(blank=True, default='', to='rango.Category'),
        ),
    ]
