# Generated by Django 2.1.5 on 2021-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20210804_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='likeNumber',
            field=models.IntegerField(default=0),
        ),
    ]
