# Generated by Django 2.1.5 on 2021-08-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_page_likenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likedPages',
            field=models.ManyToManyField(blank=True, default='', to='rango.Page'),
        ),
    ]
